### ISSUE TITLE
Make (compile) question

### ISSUE THREAD

**Issue by blindfuzzy** [marcobambini/gravity#157]
@marcobambini is there anyway to remove the "-c" when running 'make' to compile gravity? I've been poking around the make file to no avail. 

`cc -Isrc/compiler/ -Isrc/runtime/ -Isrc/shared/ -Isrc/utils/ -O2 -std=gnu99 -fgnu89-inline -fPIC -DBUILD_GRAVITY_API   -c -o src/compiler/gravity_lexer.o src/compiler/gravity_lexer.c`

The reason I am asking is because I am trying to link a custom fuzzer to gravity, but the "-c" in there is causing issues.

**Comment by rwhitworth** [comment]
Do you need to link it with each individual .o file or only with the final gravity binary?

**Comment by marcobambini** [comment]
Hi guys, sorry for the late reply.
I think that @rwhitworth is right, Gravity does not need to link each individual file and so the -c flag could be removed. @blindfuzzy have you tried to remove it? Does it continue to compile?

**Comment by ibara** [comment]
The `-c` flag is something `make` adds automatically when it sees it has to make `OBJS`. `make` knows how to turn .c files into .o files, and iterates through the list it is given. The only way to do that is to do it one at a time. That's why you don't see an option to remove it: it's built-in knowledge that `make` has. And that's a good thing: the alternative is to glob all the source files into a single `make` variable and pass that directly to the compiler.

You could try to add your own targets to the `Makefile` like this:
```
fuzzer: $(OBJS) $(GRAVITY_SRC} fuzzer-src.c
        $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^
```
Where `fuzzer` is the name you want your executable to be and `fuzzer-src.c` is the name of the C file the source code of your fuzzer lives. You'll also have to remove the main() function from `src/cli/gravity.c` to prevent main from having two definitions (which it can't have).

More than one C file for your fuzzer? Try this:
```
FUZZSRCS = fuzzer1.c fuzzer2.c fuzzer3.c ... fuzzern.c
FUZZOBJS = $(FUZZSRCS:.c=.o)

fuzzer: $(OBJS) $(GRAVITY_SRC} $(FUZZOBJS)
        $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^
```
Note too that a lot of this syntax is unportable GNU make nonsense, so perhaps learning how to do these things with POSIX make would be worth your while too.

Or, the best option would be to simply link your files to the gravity library (see the `lib` target). Though it only makes a shared object: if you want to link and forget about everything, you'll need to create a static gravity library and link to that. Perhaps building a static library should be added to the `lib` target.

**Comment by marcobambini** [comment]
Thanks a lot for the explanation @ibara
