### ISSUE TITLE
Syntax error when SEMICOLON_IS_OPTIONAL is false

### ISSUE THREAD

**Issue by marmotini** [marcobambini/gravity#192]
When `SEMICOLON_IS_OPTIONAL` is turned off,  some statements fails with syntax errors:
```
func foo () { 
    var bar = func() { return 2*2; };

    return bar();
};

func main() {
    System.print(foo());
};
```

Output:
```
SYNTAX ERROR on 0 (4,5): Expected ; but found return.
```

Expected output:
```
4
```

Not sure I'm doing the semi-colon rule correctly though. This is only happening with functions.

**Comment by marcobambini** [comment]
Good catch @marmotini, the issue has been fixed by https://github.com/marcobambini/gravity/commit/a8b54e71e07ffb463fdcdf1d5f2fdedf47aca34d.
Please note that most of the unit test fail when SEMICOLON_IS_OPTIONAL is turned off (we simply omitted most of them). I'll plan to remove that macro in the near future and make SEMICOLON OPTIONAL by default.
