### ISSUE TITLE
Ability to add extra include dirs on command line?

### ISSUE THREAD

**Issue by ibara** [marcobambini/gravity#205]
Hi!
I finally looked into the one remaining test failure on OpenBSD, `include_test.gravity`. When I run the `unittest` binary from the gravity top-level directory, this test fails because it cannot find the `test.inc` file. However when I manually `cd` into `test/unittests` and run `gravity include_test.gravity`, the test succeeds (and produces the correct result of 90). I might just be missing it, but the usual `-I` command to include other directories in the include path search doesn't seem to work. Let me know if I'm just missing something.

Thanks!

**Comment by marcobambini** [comment]
Hi @ibara,
the problem is the callback_read in the file unittest.c.
Basically it should be extended in order to take care of more cases than the default one.

There is a comment in that function that explains current limitation:
`// this unittest is able to resolve path only next to main test folder (not in nested folders)`

It works fine when you pass full path to unit-test folder to the unittest executable but I am quite sure that #include fails in any other case.

Please note that this is a minor issue since it does not affect the core language itself but only the unittest command line utility.

Would you like to improve it?

**Comment by ibara** [comment]
I will probably take a stab at it at some point, but it might take a while.
It would be nice to have eventually, especially if #33 or #42 end up happening.
(But I'll close for now, and re-open when that eventually happens.)
