### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [marcobambini/gravity#228]
I would like to point out that an identifier like “[`__GRAVITY_VALUES__`](https://github.com/marcobambini/gravity/blob/c4f143d7ef547dabea82767f41840c0df6a53c62/src/shared/gravity_value.h#L9 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by marcobambini** [comment]
I have to admit that I didn't know about that standard, thanks for the useful link.
Seems more a philosophical issue than a real one because I prefixed every macro identifier with GRAVITY. Not sure if the macros will be adjusted, I'll put the request on hold in order to better think about it.
Thanks a lot.
