### ISSUE TITLE
unlimit recursive depth

### ISSUE THREAD

**Issue by frokaikan** [marcobambini/gravity#237]
This will cause an endless loop:

class foo {
        func f1() {return 10;}
}
func main() {
        var obj = foo();
        var n1 = obj.f1();

        func test() {return 1000;}
        obj.bind("f2", main);
        var n2 = obj.f2();                              

        obj.bind("f3", {return 10000;});
        var n3 = obj.f3();                              

        obj.unbind("f2");
        obj.bind("f2", {return 50000;});
        var n4 = obj.f2();                              

        return n1+n2+n3+n4;
}

I think there should be a recursive depth limit (such as 1024?)

**Comment by marcobambini** [comment]
@frokaikan Have you edited this post? Because I received another sample code:

```swift
func f(a) {
    System.print(a);
    return f(a-1);
}

func main() {
    return f(0);
}
```

This is an unlimited loop because the user decided that it should be an unlimited loop.
There is no unique way I can limit the number of recursive calls because this is not probably what an user expects. For example:

```swift
func fibonacci (n) {
    if (n<2) return n;
    return fibonacci(n-2) + fibonacci(n-1);
}

func main() {
    return fibonacci(30);
}
```

In this case the fibonacci function is recursively called more than 2.6 million times. How can I arbitrary set a 2014 limit?

**Comment by frokaikan** [comment]
Eh, that is not me... I just want to know if I can set or modify the recursive depth limit.
Maybe there is someone want to know just the same things...

**Comment by marcobambini** [comment]
Fixed by https://github.com/marcobambini/gravity/commit/244c758498bb414562edac67a847001eae1725e3

You can now control max depth recursion with **System.maxRecursionDepth**:
```swift

func f(a) {
    return f(a-1);
}

func main() {
    System.maxRecursionDepth = 1024;
    return f(0);
}

// RUNTIME ERROR: Max recursion depth exceeded for func f (limit is set to 1024)
```

**Comment by frokaikan** [comment]
Thanks!
