### ISSUE TITLE
gcc -Wdiv-by-zero

### ISSUE THREAD

**Issue by ibara** [marcobambini/gravity#272]
Hi --

Building gravity on OpenBSD with gcc-8.3.0 triggers divide by zero warnings.
Indeed too test 672 now triggers a segfault, though I don't know if this segfault is related to the divide by zero or not.

Thanks.
[gravity.txt](https://github.com/marcobambini/gravity/files/3081912/gravity.txt)

**Comment by marcobambini** [comment]
Hi @ibara, it is a false positive because in case of the division the CHECK_ZERO macro performs the necessary sanity check of the register.

I re-run all the unit test on my mac and everything worked fine:

672	Test file: id_000126_sig_08_src_001324_op_flip1_pos_5.gravity
	Test path:test/fuzzy/2017-04-04/id_000126_sig_08_src_001324_op_flip1_pos_5.gravity
	RUNTIME ERROR: Reminder by 0 error.
	SUCCESS

Don't know why it crashes in your case.

**Comment by ibara** [comment]
Alright that's helpful. They must not be related, just popped up at the same time.
Will investigate and write back.

**Comment by marcobambini** [comment]
@ibara do you think I can close this issue?

**Comment by ibara** [comment]
Yeah sure I'll open a new one about the failing test when I find the cause.
