### ISSUE TITLE
Potential bug issue(memcpy:Does not check for buffer overflows when copying to destination)

### ISSUE THREAD

**Issue by SpiralBL0CK** [marcobambini/gravity#288]
![Screenshot from 2019-12-25 23-42-49](https://user-images.githubusercontent.com/25670930/71450743-52f79880-2770-11ea-9455-c56abd7b6986.png)
Upon scanning the project with a static analyzer(flawfinder) it has been revealed that 
![Screenshot from 2019-12-25 23-44-03](https://user-images.githubusercontent.com/25670930/71450807-fd23f000-2771-11ea-950f-cfff68c3fbc5.png)
 integer overflow may occur if one uses json_parse_ex()  since the image shows that it copies into state.setting an unsigned long variable(setting).Now i might be wrong if i am please write me an email at vladvatafu9@gmail.com providing an explanation why I am wrong cause I'm an teenager interested in static analysis which is still learning and does not have many experience with code review.Thank you for your allocated time,sry for the trouble.

**Comment by marcobambini** [comment]
`state.settings` and `settings` are both of type type `json_settings`. Your static analyzer reported a false positive because `settings` is a pointer to a` json_settings` struct and it incorrectly thinks that an unsigned long variable is being copied. Please note that memcpy requires src and dest to be pointers so that code is correct.

**Comment by SpiralBL0CK** [comment]
Ok thank you for looking up this and sry for bothering you and maybe
wasting your time.Enjoy the holidays.God bless and have a nice day!

Best regards,

Vlad
