### ISSUE TITLE
Question regarding release of native type instances.

### ISSUE THREAD

**Issue by iSLC** [marcobambini/gravity#290]
In the c++ example i noticed that a single function `static void object_free (gravity_vm *vm, gravity_object_t *obj)` is used to release all object instances. Is the current implementation limited to just one function for all types or you can bind individual functions/closures for each class? (_not instance!_)

Having one function to clean all objects will add a bit of indirection because you will have store a function pointer which acts as a deleter alongside each instance. Kinda like:

```c
typedef struct AppInstance {
    void* p; // pointer to instance.
    void (*f)(void *); // pointer to function used to delete this instance.
}  *HAPPINST;
```

Is there some way, for example, the same way you bind `GRAVITY_INTERNAL_EXEC_NAME` to bind one for destruction?

I remember seeing something a while back when I was looking at the code. But now I feel like i'm imagining things because i can't find that anymore.

**Comment by marcobambini** [comment]
Hi @iSLC I am not sure to understand your question but I'll try to explain a bit what happens under the hood.

When you register a new class from a foreign language (like in the C++ example) you have to register a delegate callback that will be called each time an object is freed by the garbage collector.

So, the CG will determine when a Gravity object is no longer needed and it can be freed.
At this point `gravity_value_free` is called (in gravity_value.c) and if the value is an object then `gravity_object_free` is called.

In the if statements you can find the `gravity_instance_free` call and this is where a check on the `xdata` field is performed.

`xdata` set means that there is an external instance connected (in this specific case it is a C++ instance) and in order to give to C++ the possibility to clean-up the object and release its memory and additional check is performed on the registered `bridge_free` delegate callback.

If the callback is registered than it means that Gravity can call it passing the native C++ instance as parameter. Using `xdata` and `bridge_free` delegate, Gravity can be sure to not have memory leaks even in case of external languages. We use the same method in Creo where the external language is ObjC and everything works pretty well.

Hope this helps.

**Comment by iSLC** [comment]
That's exactly what I was trying to say. That there is a single free function used globally, regardless of type.

Assuming I have these 3 types:
```cpp
class Vec2 { float x,y; };
class Vec3 { float x,y,z; };
class Vec4 { float x,y,z,w; };

static bool vec2_create(gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex) { /*details...*/ }
static bool vec3_create(gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex) { /*details...*/ }
static bool vec4_create(gravity_vm *vm, gravity_value_t *args, uint16_t nargs, uint32_t rindex) { /*details...*/ }

void register_cpp_classes (gravity_vm *vm) {
    // create vec2 class
    {
	    gravity_class_t *vec_class = gravity_class_new_pair(vm, "vec2", NULL, 0, 0);
	    gravity_class_t *vec_class_meta = gravity_class_get_meta(vec_class);
	    gravity_class_bind(vec_class_meta, GRAVITY_INTERNAL_EXEC_NAME, NEW_CLOSURE_VALUE(ve2_create));
	    gravity_vm_setvalue(vm, "vec2", VALUE_FROM_OBJECT(vec_class));
    }
    // create vec3 class
    {
	    gravity_class_t *vec_class = gravity_class_new_pair(vm, "vec3", NULL, 0, 0);
	    gravity_class_t *vec_class_meta = gravity_class_get_meta(vec_class);
	    gravity_class_bind(vec_class_meta, GRAVITY_INTERNAL_EXEC_NAME, NEW_CLOSURE_VALUE(vec3_create));
	    gravity_vm_setvalue(vm, "vec3", VALUE_FROM_OBJECT(vec_class));
    }
    // create vec4 class
    {
	    gravity_class_t *vec_class = gravity_class_new_pair(vm, "vec4", NULL, 0, 0);
	    gravity_class_t *vec_class_meta = gravity_class_get_meta(vec_class);
	    gravity_class_bind(vec_class_meta, GRAVITY_INTERNAL_EXEC_NAME, NEW_CLOSURE_VALUE(vec4_create));
	    gravity_vm_setvalue(vm, "vec4", VALUE_FROM_OBJECT(vec_class));
    }
}
```
And a single function to free:
```cpp
static void object_free (gravity_vm *vm, gravity_object_t *obj) {
    gravity_instance_t *instance = (gravity_instance_t *)obj;
    
    // get xdata (which is a cpp Vec2/3/4 instance)
    Vec2 *r = (Vec2 *)instance->xdata;
    // ^ HERE: will execute for vec2, vec3 and vec4
    // explicitly free memory
    delete r; // I'm calling delete on vec2 but it may as well be vec3 or vec4
}
```

However, I just realized that I could probably store individual free functions in the `xdata` for the class. And then retrieve the class from the instance and easily gain access to the deleter from there.

Something like:
```cpp
class Vec2 { float x,y; };
class Vec3 { float x,y,z; };
class Vec4 { float x,y,z,w; };

template <class T> void instance_free (gravity_vm *vm, void *ptr) {
	auto inst = reinterpret_cast<T*>(ptr);
	delete inst;
}

void register_cpp_classes (gravity_vm *vm) {
    // create vec2 class
    {
	    gravity_class_t *vec_class = gravity_class_new_pair(vm, "vec2", NULL, 0, 0);
	    gravity_class_setxdata(vec_class, reinterpret_cast<void*>(&instance_free<vec2>));
    }
    // create vec3 class
    {
	    gravity_class_t *vec_class = gravity_class_new_pair(vm, "vec3", NULL, 0, 0);
	    gravity_class_setxdata(vec_class, reinterpret_cast<void*>(&instance_free<vec3>));
    }
    // create vec4 class
    {
	    gravity_class_t *vec_class = gravity_class_new_pair(vm, "vec4", NULL, 0, 0);
	    gravity_class_setxdata(vec_class, reinterpret_cast<void*>(&instance_free<vec4>));
    }
}

static void object_free (gravity_vm *vm, gravity_object_t *obj) {
	if (OBJECT_ISA_INSTANCE(obj)) {
    	gravity_instance_t *instance = (gravity_instance_t *)obj;
    	auto free_fp =reinterpret_cast< void (*) (gravity_vm *vm, void *ptr) >(instance->objclass->xdata);
    	if (free_fp)
    		free_fp(vm, instance->xdata);
	}
}
```

But a little more elaborate and with some safeguard. Anyway, thanks for the information.

**Comment by marcobambini** [comment]
You should always store the instance in the xdata and then in the object_free you could use the c++ casting functions to determine the right class. Most of the time this is not necessary because a delete is more than sufficient... but I agree that sometimes a cast to know the c++ class could be necessary.

In your specific example all you need to do is a call to:
```delete r;```
in object_free, and the instance will be correctly freed regardless if it is a Vec2, Vec3 or Vec4 instance.
