### ISSUE TITLE
How to define enums from C

### ISSUE THREAD

**Issue by foobit** [marcobambini/gravity#309]
Using the C _Embedding API_, how would one define a Gravity enum to the VM?

**Comment by marcobambini** [comment]
There is no such API because enums are compiled and replaced by literal values at compile time.
What you can do is to use the precode_callback (in the gravity_delegate_t) to pass the text representation of your enums.

Does this solve your issue?
If not, can you please explain me what you are trying to achieve (so I can find out another way).

**Comment by foobit** [comment]
The `precode_callback` will work for this case. However, it is a different workflow than using the API to expose classes and functions.  I would have to emit or have a separate gravity file to match the C enum than apply that to the `gravity_delegate_t`.

I will think about expanding the usage of the `precode_callback`.  I am already planning to have a large number of gravity files I want to expose via `precode_callback`.

The current workflow:
- Read all gravity files as text
- Append them as a single string
- Keep that string in memory use it as a return value for the `precode_callback`

Ideally having a common way to emit numerous Gravity scripts or bytecode would help. See https://github.com/marcobambini/gravity/issues/234#issuecomment-447720300

**Comment by marcobambini** [comment]
When you serialize gravity source code the output is a JSON file with bytecode embedded. That file could be represented by a C string. This is how things currently work. I am open to suggestions/proposals to offer better API and functionalities.
Enum is really a special case because enum values are replaced at compile time (and not at runtime), which is probably a bit odd for a dynamic language like Gravity.

**Comment by foobit** [comment]
Ah I see it now. I'll look into adding the gravity cli into my build system. E.g. Generate the bytecode at compile time and include it into my C source.

That will automate it nicely.
