### ISSUE TITLE
Constructor Issue

### ISSUE THREAD

**Issue by SuperWangKai** [marcobambini/gravity#324]
It seems we cannot construct an object of the same class inside a constructor. It is common when e.g. constructing a nodes tree/linked list, etc.

Following code does NOT run:
```swift
class MyClass {
    var depth = 0;
    var object = null;

    func init(d) {
        depth = d;
        d -= 1;
        if (d > 0)
        {
            object = MyClass(d); // This is incorrect in current implementation of gravity
        }
    }

    func print_info() {
        System.print("\(depth)");
        if (object) {
            object.print_info();
        }
    }
}

func main() {
    var a = MyClass(3);
    a.print_info();
}
```

While this work-around runs:
```swift
class MyClass {
    var depth = 0;
    var object = null;

    func init_me(d) { // Work-around: here we use normal function to initialize 
        depth = d;
        d -= 1;
        if (d > 0)
        {
            object = MyClass(); // Now, it works.
            object.init_me(d);
        }
    }

    func print_info() {
        System.print("\(depth)");
        if (object) {
            object.print_info();
        }
    }
}

func main() {
    var a = MyClass();
    a.init_me(3); // Work-around, call init_me to create object in depth
    a.print_info();
}
```

![image](https://user-images.githubusercontent.com/15721569/96622102-18cd3800-133c-11eb-952a-ce9483470a67.png)

Additionally, I also find that there are some cases, the compiler/vm does not throw any error message when there is error, such as in the case of this issue.

Thanks,
Kai

**Comment by marcobambini** [comment]
The real error was that no error was reported. I fixed the issue with https://github.com/marcobambini/gravity/commit/5f7c0aa62fc9d513f509a00965b83c717427ef07

In my opinion this code should not be allowed because it will end up in an infinite loop.
I just checked this sample code with Swift and the result is an infinite loop:
```swift
class Foo {
    var f: Foo;
    
    init() {
        f = Foo();
    }
}

var a = Foo();
```

The good news is that Gravity correctly reports a `SEMANTIC ERROR on 0 (11,25): Infinite loop detected in init func.`
Do you know if other languages permit that feature?
