### ISSUE TITLE
Should Gravity's standard library be written in Gravity?

### ISSUE THREAD

**Issue by neysofu** [marcobambini/gravity#33]
Gravity built-ins are currently hardcoded into the compiler. I believe it would be better to port the non-primitives to Gravity so that people can still contribute to Gravity's core without being familiar with the internal details of the compiler.

These are some examples of data structures that could easily be implemented:
- hash tables,
- binary trees,
- sets and other collections.

**Comment by Dohxis** [comment]
I strongly agree with this! Contributing to Gravity would become way easier.

**Comment by badcc** [comment]
Go does this; however, Lua [does not](https://www.lua.org/manual/5.3/manual.html#6) in order to squeeze extra speed out. The difference is that Lua (& Gravity) are interpreted, while Go is compiled (and interpreted.. but people who want speed will compile). Since one of Gravity's claims is "high performance," I'm tempted to say leave it in C rather than move to Gravity.

**Comment by Dohxis** [comment]
But as mentioned [here](https://github.com/marcobambini/gravity/issues/25) writing Gravity compiler in Gravity is the ultimate goal. I think it also means writing standart library as well.

**Comment by nanalan** [comment]
I'd love for at least _support_ for this, since I'd love to contribute to the standard library.
