### ISSUE TITLE
Question regarding the GC

### ISSUE THREAD

**Issue by untoldengine** [marcobambini/gravity#380]
Hi @marcobambini 

Hope you are doing well. I have a question regarding the garbage collector in Gravity.

When is an object eligible to be garbage-collected in Gravity? I ask because I'm noticing that once an object goes out of scope, the corresponding gravity_object_free function is not being called.

Furthermore, I noticed that objects that are out of scope do get collected by the GC if I call this function:

```
gravity_gc_start(vm);
```

Do I have to explicitly call this function for the GC to start?

P.S. this is how my delegate is set up:

```
// setup delegate
    delegate = {
        .error_callback = reportError,
        .bridge_free = object_free,
        .loadfile_callback = loadFileCallback
    };
```

Thank you

**Comment by marcobambini** [comment]
Hi @untoldengine

I am good, thanks. I hope you are doing well too.

Each time an object is allocated the function `gravity_vm_transfer` is called, which end-up calling `gravity_gc_transfer` (in gravity_vm.c).

In `gravity_gc_transfer` there is some debug code that you can skip, but the most important code is the line:
```c
if (vm->memallocated >= vm->gcthreshold) gravity_gc_start(vm);
```

```c
vm->memallocated   \\ total memory allocated so far
vm->gcthreshold    \\ threshold set to trigger the GC (default set to 5MB) 
```

So, to reply to your question, the GC is called each time the **internal** memory usage is higher than 5MB (vm->gcthreshold).

The key **internal** is important here because the VM cannot know how much memory your C++ takes, so you can have tons of huge C++ objects that take only a few bytes of **internal** memory (just a pointer to a C++ object).

You could reduce the gcthreshold value, but there will be a risk of performance penalties due to the overhead of the GC.
Another approach that I recommend is to manually call `gravity_vm_memupdate` from your C++ to exactly tell Gravity how much memory your C++ code is allocating.

Hope this helps.

**Comment by untoldengine** [comment]
Hi @marcobambini 

Ah, that explains it. I was wondering why the objects were not been garbage collected. Thank you

**Comment by marcobambini** [comment]
Hi @untoldengine, can we close this issue?
How is your project doing?

**Comment by untoldengine** [comment]
Yes. We can close the issue. 

Still working on it. :)
